docs: add archive warning to readme
cypress-io/cypress-webpack-preprocessor pull request #109
Opened 2020-09-29 15:34 UTC by panzarino

Adds an archive warning to the readme and redirects users to the new package location

Repo must be officially archived after merge

2020-09-29 17:51 UTC, JessicaSachs requested changes
The next steps are to also delete all the files in the repository, leaving only this README.md -- can you update the PR to delete all the files?

2020-09-29 18:13 UTC, chrisbreiding submitted a review, later dismissed

2020-09-29 18:13 UTC, chrisbreiding commented on README.md
> +# :warning: THIS REPO HAS BEEN ARCHIVED :warning:
```suggestion
# :warning: THIS REPO HAS BEEN MOVED :warning:
```

At first glance, "archived" sounds like we're killing off this project, so I think we should say it's been "moved".

2020-09-29 18:48 UTC, panzarino commented
Is there a better emoji or formatting that we could use here? I'm afraid that this comes off as if we deprecated the project: 

<img width="959" alt="Screen Shot 2020-09-29 at 2 47 26 PM" src="https://user-images.githubusercontent.com/7033952/94602343-badc9180-0262-11eb-9026-b358d4dce57a.png">

2020-09-30 23:04 UTC, JessicaSachs commented
Yeah, a moving truck

2020-09-30 23:10 UTC, JessicaSachs approved these changes

2020-09-30 23:34 UTC, brian-mann approved these changes

2020-09-30 23:49 UTC, chrisbreiding approved these changes

2020-10-01 15:23 UTC, merged